### ISSUE TITLE
Latest version won't allow OpenAI > 1.0

### ISSUE THREAD

**Issue by gregdetre** [simonw/llm#384] opened 2023-12-31 15:55 UTC
Hi Simon,

The latest version of LLM (0.12 as of 31 Dec 2023) has [pinned the OpenAI library to `< 1.0`](https://github.com/simonw/llm/blob/main/setup.py#L40). This is the version before they changed their interface to `from openai import OpenAI`, so it's out of date with the latest code snippets etc.

(I did try switching back to LLM 0.11, which doesn't have this restriction, but that hasn't heard of the `gpt-4-1106-preview` model, i.e. GPT-4-Turbo).

I haven't looked to see how much work it would be to upgrade to the new OpenAI interface, so there may be a good reason why you haven't got round to it.

Thanks for all your work on this. It's a lovely interface.

**Comment by tm-kn** [comment] 2024-01-02 17:12
I believe this is a duplicate of #325.

**Comment by thiswillbeyourgithub** [comment] 2024-01-08 12:55
Maybe a simpler way would be simply to use [litellm](https://docs.litellm.ai/docs/providers).

They make a python package that can be used to call lots of different backends. I think it would be better for llm to use litellm to handle API call than to keep relying on people creating and maintaining plugins for every backend.

They also support caching, embeddings, async calls, etc.

**Comment by simonw** [comment] 2024-01-26 01:45
Yes, closing as a dupe.

**Closed by simonw** 2024-01-26 01:45 UTC
